#Render database connection

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d7ggnj471suc73ajlkig-a.virginia-postgres.render.com/veebipood_database_t972
spring.datasource.username=veebipood_user
spring.datasource.password=1